export const CountryLocalizedNames: any = {
    en: {
        HUNGARY: 'Hungary',
        ROMANIA: 'Romania',
        SERBIA: 'Serbia',
        UNITED_KINGDOM: 'United Kingdom',
        CROATIA: 'Croatia',
        SLOVENIA: 'Slovenia',
        AUSTRIA: 'Austria',
        SLOVAKIA: 'Slovakia',
        UKRAINE: 'Ukraine',
        SPAIN: 'Spain',
    },
    hu: {
        HUNGARY: 'Magyarország',
        ROMANIA: 'Románia',
        SERBIA: 'Szerbia',
        UNITED_KINGDOM: 'Egyesült Királyság',
        CROATIA: 'Horvátország',
        SLOVENIA: 'Szlovenia',
        AUSTRIA: 'Ausztria',
        SLOVAKIA: 'Szlovákia',
        UKRAINE: 'Ukrajna',
        SPAIN: 'Spanyolország',
    },
};
